//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Help.IndexStrings", typeof(IndexStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Animator&quot; - person who primarily animates PVs..
        /// </summary>
        public static string GlArtistAnimator {
            get {
                return ResourceManager.GetString("GlArtistAnimator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Circle&quot; - group that self-publishes and sells albums only at doujin events (Comiket or Vocaloid Master)..
        /// </summary>
        public static string GlArtistCircle {
            get {
                return ResourceManager.GetString("GlArtistCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed artist entries should meet the following criteria:.
        /// </summary>
        public static string GlArtistCompletedTitle {
            get {
                return ResourceManager.GetString("GlArtistCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artist has a description OR at least one external link (to a wiki, artist&apos;s NND MyList etc.).
        /// </summary>
        public static string GlArtistHasDescription {
            get {
                return ResourceManager.GetString("GlArtistHasDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Label&quot; - a commercial company that publishes albums for other artists..
        /// </summary>
        public static string GlArtistLabel {
            get {
                return ResourceManager.GetString("GlArtistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artist has at least one name whose language option isn&apos;t &quot;Unspecified&quot;..
        /// </summary>
        public static string GlArtistNameNotUnspecified {
            get {
                return ResourceManager.GetString("GlArtistNameNotUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Other group&quot; - group that releases albums via Labels..
        /// </summary>
        public static string GlArtistOtherGroup {
            get {
                return ResourceManager.GetString("GlArtistOtherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Other individual&quot; - other people such as lyricists and illustrators..
        /// </summary>
        public static string GlArtistOtherIndividual {
            get {
                return ResourceManager.GetString("GlArtistOtherIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Other vocalist&quot; - human singers (NND vocalists)..
        /// </summary>
        public static string GlArtistOtherVocalist {
            get {
                return ResourceManager.GetString("GlArtistOtherVocalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When adding pictures to artists, keep in mind all the pictures should be related to the artist himself, not his works. Do not upload album covers for artist entries. 
        /// That said, there is no common rule for choosing the main picture of an artist. Photos of the artist himself as well as official logos are preferred. You may upload any number of these pictures as additional pictures for the artist, provided that they&apos;re relevant enough.
        ///Copyrighted pictures or pictures of artists may be taken down if the co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GlArtistPictureChoosing {
            get {
                return ResourceManager.GetString("GlArtistPictureChoosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist pictures.
        /// </summary>
        public static string GlArtistPictureTitle {
            get {
                return ResourceManager.GetString("GlArtistPictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Producer&quot; - the person who created the song (and in the case of a Vocaloid song, usually the vocals as well using Vocaloid). Not necessarily the original composer..
        /// </summary>
        public static string GlArtistProducer {
            get {
                return ResourceManager.GetString("GlArtistProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every artist has a classification which also determines the artist&apos;s default roles. Roles can be overridden per album and per song -basis, but in many cases the artist is involved only in one role..
        /// </summary>
        public static string GlArtistRoles {
            get {
                return ResourceManager.GetString("GlArtistRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists, producers and Vocaloids.
        /// </summary>
        public static string GlArtistsTitle {
            get {
                return ResourceManager.GetString("GlArtistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist type isn&apos;t &quot;Unspecified&quot;..
        /// </summary>
        public static string GlArtistTypeNotUnspecified {
            get {
                return ResourceManager.GetString("GlArtistTypeNotUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist types.
        /// </summary>
        public static string GlArtistTypesTitle {
            get {
                return ResourceManager.GetString("GlArtistTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct download links to media files (such as .mp3) are generally not allowed, even if they&apos;re official and legal. If the song/video is officially distributed, link to the artist&apos;s official download page (for example on piapro) instead..
        /// </summary>
        public static string GlAvoidDirectDownload {
            get {
                return ResourceManager.GetString("GlAvoidDirectDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid submitting entries that already exist in the database. Duplicates have to be deleted or merged by the staff..
        /// </summary>
        public static string GlAvoidDuplicates {
            get {
                return ResourceManager.GetString("GlAvoidDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download links to illegal file-sharing sites that provide no useful information (like Mediafire/Megaupload/Torrents) are NOT allowed. Links to informative blogs/forums/wikis (like MikuDB/Miku;Zen) ARE allowed..
        /// </summary>
        public static string GlAvoidFileSharing {
            get {
                return ResourceManager.GetString("GlAvoidFileSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a database for Vocaloid-related content. UTAU and Vocaloid-related collaborations are accepted, but totally unrelated content will be deleted..
        /// </summary>
        public static string GlAvoidOfftopic {
            get {
                return ResourceManager.GetString("GlAvoidOfftopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When editing entries that are finalized or approved (not drafts), make sure you have a good reason, and preferably state that reason in the edit notes unless it&apos;s obvious..
        /// </summary>
        public static string GlEditApprovedWithCaution {
            get {
                return ResourceManager.GetString("GlEditApprovedWithCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General principles.
        /// </summary>
        public static string GlGeneralTitle {
            get {
                return ResourceManager.GetString("GlGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I add new producers, albums and songs?.
        /// </summary>
        public static string GlHowCanIAddEntriesTitle {
            get {
                return ResourceManager.GetString("GlHowCanIAddEntriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;English&quot; is for official names in English and known translations of foreign names..
        /// </summary>
        public static string GlNamesEnglish {
            get {
                return ResourceManager.GetString("GlNamesEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All names should primarily be written in the original language, which usually means Japanese, but it can also be for example English or Korean. The system supports 3 language options:.
        /// </summary>
        public static string GlNamesHow {
            get {
                return ResourceManager.GetString("GlNamesHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Non-English&quot; covers original names in all languages that aren&apos;t English or romanized, for example Japanese..
        /// </summary>
        public static string GlNamesNonEnglish {
            get {
                return ResourceManager.GetString("GlNamesNonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Romanized&quot; is for foreign original names written in the Latin (western) alphabet. Usually this means Romaji..
        /// </summary>
        public static string GlNamesRomaji {
            get {
                return ResourceManager.GetString("GlNamesRomaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names and translations.
        /// </summary>
        public static string GlNamesTitle {
            get {
                return ResourceManager.GetString("GlNamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Unspecified&quot; is for names where the language doesn&apos;t matter or it&apos;s unknown. Unspecified names will never be used as display names of an entry if another name is provided..
        /// </summary>
        public static string GlNamesUnspecified {
            get {
                return ResourceManager.GetString("GlNamesUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register and use links in main navigation panel or buttons in producer, album and song list pages..
        /// </summary>
        public static string GlRegister {
            get {
                return ResourceManager.GetString("GlRegister", resourceCulture);
            }
        }
    }
}
