//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Search {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Search.IndexStrings", typeof(IndexStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album type.
        /// </summary>
        public static string AlbumType {
            get {
                return ResourceManager.GetString("AlbumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist type.
        /// </summary>
        public static string ArtistType {
            get {
                return ResourceManager.GetString("ArtistType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In my collection.
        /// </summary>
        public static string InMyCollection {
            get {
                return ResourceManager.GetString("InMyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More filters.
        /// </summary>
        public static string MoreFilters {
            get {
                return ResourceManager.GetString("MoreFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More recent than.
        /// </summary>
        public static string MoreRecentThan {
            get {
                return ResourceManager.GetString("MoreRecentThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only with PVs.
        /// </summary>
        public static string OnlyWithPVs {
            get {
                return ResourceManager.GetString("OnlyWithPVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song type.
        /// </summary>
        public static string SongType {
            get {
                return ResourceManager.GetString("SongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TagCategory {
            get {
                return ResourceManager.GetString("TagCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something....
        /// </summary>
        public static string TypeSomething {
            get {
                return ResourceManager.GetString("TypeSomething", resourceCulture);
            }
        }
    }
}
