//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Song {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DetailsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Song.DetailsStrings", typeof(DetailsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to custom list.
        /// </summary>
        public static string AddToCustomList {
            get {
                return ResourceManager.GetString("AddToCustomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to list.
        /// </summary>
        public static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate versions.
        /// </summary>
        public static string AlternateVersions {
            get {
                return ResourceManager.GetString("AlternateVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animators.
        /// </summary>
        public static string Animators {
            get {
                return ResourceManager.GetString("Animators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check NicoSound for a download link.
        /// </summary>
        public static string CheckNicoSound {
            get {
                return ResourceManager.GetString("CheckNicoSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite(s).
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} like(s).
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string Lyrics {
            get {
                return ResourceManager.GetString("Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string LyricsFrom {
            get {
                return ResourceManager.GetString("LyricsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lyrics.
        /// </summary>
        public static string LyricsLC {
            get {
                return ResourceManager.GetString("LyricsLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original media.
        /// </summary>
        public static string OriginalMedia {
            get {
                return ResourceManager.GetString("OriginalMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original version.
        /// </summary>
        public static string OriginalVersion {
            get {
                return ResourceManager.GetString("OriginalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other artists.
        /// </summary>
        public static string OtherArtists {
            get {
                return ResourceManager.GetString("OtherArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other media.
        /// </summary>
        public static string OtherMedia {
            get {
                return ResourceManager.GetString("OtherMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pools.
        /// </summary>
        public static string Pools {
            get {
                return ResourceManager.GetString("Pools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producers.
        /// </summary>
        public static string Producers {
            get {
                return ResourceManager.GetString("Producers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV.
        /// </summary>
        public static string PVDetails {
            get {
                return ResourceManager.GetString("PVDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear my rating.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Youtube.
        /// </summary>
        public static string SearchYoutube {
            get {
                return ResourceManager.GetString("SearchYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string SongDetails {
            get {
                return ResourceManager.GetString("SongDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} total score.
        /// </summary>
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on external site.
        /// </summary>
        public static string ViewExternal {
            get {
                return ResourceManager.GetString("ViewExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocalists.
        /// </summary>
        public static string Vocalists {
            get {
                return ResourceManager.GetString("Vocalists", resourceCulture);
            }
        }
    }
}
