//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Album {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DetailsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Album.DetailsStrings", typeof(DetailsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to my collection.
        /// </summary>
        public static string AddToCollection {
            get {
                return ResourceManager.GetString("AddToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string AlbumDetails {
            get {
                return ResourceManager.GetString("AlbumDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog number.
        /// </summary>
        public static string CatalogNumber {
            get {
                return ResourceManager.GetString("CatalogNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover picture.
        /// </summary>
        public static string CoverPicture {
            get {
                return ResourceManager.GetString("CoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download track info as CSV.
        /// </summary>
        public static string DownloadTrackList {
            get {
                return ResourceManager.GetString("DownloadTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit album in collection.
        /// </summary>
        public static string EditAlbumInCollection {
            get {
                return ResourceManager.GetString("EditAlbumInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label(s).
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media type.
        /// </summary>
        public static string MediaType {
            get {
                return ResourceManager.GetString("MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string MyRating {
            get {
                return ResourceManager.GetString("MyRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tracklist provided. Any registered user is able to add one..
        /// </summary>
        public static string NoTracklist {
            get {
                return ResourceManager.GetString("NoTracklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other artists.
        /// </summary>
        public static string OtherArtists {
            get {
                return ResourceManager.GetString("OtherArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned by {0}.
        /// </summary>
        public static string OwnedBy {
            get {
                return ResourceManager.GetString("OwnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producers.
        /// </summary>
        public static string Producers {
            get {
                return ResourceManager.GetString("Producers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads / crossfades.
        /// </summary>
        public static string PVs {
            get {
                return ResourceManager.GetString("PVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ratings.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release event.
        /// </summary>
        public static string ReleaseEvent {
            get {
                return ResourceManager.GetString("ReleaseEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracklist.
        /// </summary>
        public static string Tracklist {
            get {
                return ResourceManager.GetString("Tracklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in my collection.
        /// </summary>
        public static string UpdateCollection {
            get {
                return ResourceManager.GetString("UpdateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocalists.
        /// </summary>
        public static string Vocalists {
            get {
                return ResourceManager.GetString("Vocalists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlisted by {0}.
        /// </summary>
        public static string WishlistedBy {
            get {
                return ResourceManager.GetString("WishlistedBy", resourceCulture);
            }
        }
    }
}
